update workflow and selenium tests

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -73,7 +73,7 @@ jobs:
   selenium-tests:
     needs: [deploy,approve]
     if: always() && (needs.approve.result == 'success' || needs.approve.result == 'skipped')
-    runs-on: windows-latest
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: "Setup PNPM"
@@ -82,8 +82,20 @@ jobs:
         run : |
           pnpm install selenium-webdriver
           pnpm install chromedriver
+          pnpm install github-actions-toolkit
+      - uses: browser-actions/setup-chrome@latest
+      - run: chrome --version
       # - name: Set environment variable
       #   run: echo "DEPLOYED_URL=http://${{ secrets.AWS_S3_BUCKET_ANGULAR }}-${{ inputs.CI_ENV}}.s3-website-us-east-1.amazonaws.com/index.html" >> $GITHUB_ENV
 
       - name: Run Selenium tests
         run: node tests/selenium_test.js http://${{ secrets.AWS_S3_BUCKET_ANGULAR }}-${{ inputs.CI_ENV}}.s3-website-us-east-1.amazonaws.com/index.html
+      - name: Check test result
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "Selenium tests passed!"
+          else
+            echo "Selenium tests failed!"
+            /usr/bin/env node -e "require('github-actions-toolkit').Toolkit().exit.failure('Selenium tests failed!');"
+            exit 1
+          fi
