add test result validation

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -90,17 +90,30 @@ jobs:
 #http://${{ secrets.AWS_S3_BUCKET_ANGULAR }}-${{ inputs.CI_ENV}}.s3-website-us-east-1.amazonaws.com/index.html
 
       - name: Run Selenium tests
-        run: node tests/selenium_test.js http://the-internet.herokuapp.com &
+        run: node tests/selenium_test.js http://the-internet.herokuapp.com > test_results.txt
       - name: Wait for tests to finish
         run: npx wait-on http://the-internet.herokuapp.com --timeout 5000 
-      - name: Check selenium test result
+      # - name: Check selenium test result
+      #   run: |
+      #     if [ $? -eq 0 ]; then
+      #       echo "Selenium tests passed!"
+      #     else
+      #       echo "Selenium tests failed!"
+      #       exit 1
+      #     fi
+      - name: Read test results
         run: |
-          if [ $? -eq 0 ]; then
-            echo "Selenium tests passed!"
-          else
-            echo "Selenium tests failed!"
-            exit 1
-          fi
+          test_results=$(cat test_results.txt)
+          echo "Test Results: $test_results"
+      - name: Validate test results
+        run: |
+            if grep -q "error" test_results.txt; then
+              echo "Error found in test results!"
+              exit 1
+            else
+              echo "No errors found in test results."
+            fi
  # /usr/bin/env node -e "require('actions-toolkit').Toolkit().exit.failure('Selenium tests failed!');"
+ #/usr/bin/env node -e "require('github-actions-toolkit').Toolkit().exit.failure('Error found in test results!');"
  #pnpm install actions-toolkit
           
